name: prayer_app
description: Islamic Prayer Times Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  intl: ^0.20.2
  geolocator: ^13.0.2
  shared_preferences: ^2.5.2
  hijri: ^3.0.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Add sound assets for notifications
  assets:
    - assets/sounds/
    
  # Uncomment and add the following to include sound files
  # fonts:
  #   - family: MyIcons
  #     fonts:
  #       - asset: fonts/MyIcons.ttf